POST http://localhost:8101/public/login
content-type: application/json

{
    "steamId": 76561198393504470,
    "displayName": "Foxx"
}

###

GET http://localhost:8101/game/locations
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo0LCJzdGVhbUlkIjo3NjU2MTE5ODM5MzUwNDQ2MCwicHJpbWFyeUxvY2F0aW9uIjp7ImlkIjoxfSwiZGlzcGxheU5hbWUiOiJGb3h4IiwibGV2ZWwiOjEsImNyZWRpdHMiOjAsInhwIjowfSwiaWF0IjoxNzIwODc3NjMwLCJleHAiOjIwMzY0NTM2MzB9.Xf0dJLWUhUtJvvvMc6h6JYke7N5G0_js_Yc4LoUlHMo

###

GET http://localhost:8101/game/locations/2-2
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo0LCJzdGVhbUlkIjo3NjU2MTE5ODM5MzUwNDQ2MCwicHJpbWFyeUxvY2F0aW9uIjp7ImlkIjoxfSwiZGlzcGxheU5hbWUiOiJGb3h4IiwibGV2ZWwiOjEsImNyZWRpdHMiOjAsInhwIjowfSwiaWF0IjoxNzIwODc3NjMwLCJleHAiOjIwMzY0NTM2MzB9.Xf0dJLWUhUtJvvvMc6h6JYke7N5G0_js_Yc4LoUlHMo


###

POST https://api-na.orcwood.com/public/login
content-type: application/json

{
    "steamId": 76561198393504470,
    "displayName": "Foxx"
}

###
GET https://api-new-america-ieqetiq36q-uc.a.run.app/game/locations
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo2LCJ1dWlkIjoiYjE1YjI0ZTktMTMwNy0xMWYwLWE1NWQtZTY3M2UzZmJhYzVkIiwic3RlYW1JZCI6NzY1NjExOTgzOTM1MDQ0NjAsInByaW1hcnlMb2NhdGlvbiI6eyJpZCI6MjA0fSwiZGlzcGxheU5hbWUiOiJGb3h4IiwibGV2ZWwiOjEsImNyZWRpdHMiOjAsInhwIjowfSwiaWF0IjoxNzQzOTU4NDIwLCJleHAiOjIwNTk1MzQ0MjB9.HMP3tWluPow8Yh-_D5ijgwwW-mdkP1vZ3eF4FbH2l8c

###
GET https://api-new-america-ieqetiq36q-uc.a.run.app/game/heightmap/1/1/500
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo2LCJ1dWlkIjoiYjE1YjI0ZTktMTMwNy0xMWYwLWE1NWQtZTY3M2UzZmJhYzVkIiwic3RlYW1JZCI6NzY1NjExOTgzOTM1MDQ0NjAsInByaW1hcnlMb2NhdGlvbiI6eyJpZCI6MjA0fSwiZGlzcGxheU5hbWUiOiJGb3h4IiwibGV2ZWwiOjEsImNyZWRpdHMiOjAsInhwIjowfSwiaWF0IjoxNzQzOTU4NDIwLCJleHAiOjIwNTk1MzQ0MjB9.HMP3tWluPow8Yh-_D5ijgwwW-mdkP1vZ3eF4FbH2l8c
