POST http://localhost:8101/public/login
content-type: application/json

{
    "steamId": 76561198393504470,
    "displayName": "Foxx"
}

###

GET http://localhost:8101/game/locations
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo0LCJzdGVhbUlkIjo3NjU2MTE5ODM5MzUwNDQ2MCwicHJpbWFyeUxvY2F0aW9uIjp7ImlkIjoxfSwiZGlzcGxheU5hbWUiOiJGb3h4IiwibGV2ZWwiOjEsImNyZWRpdHMiOjAsInhwIjowfSwiaWF0IjoxNzIwODc3NjMwLCJleHAiOjIwMzY0NTM2MzB9.Xf0dJLWUhUtJvvvMc6h6JYke7N5G0_js_Yc4LoUlHMo

###

GET http://localhost:8101/game/locations/2-2
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo0LCJzdGVhbUlkIjo3NjU2MTE5ODM5MzUwNDQ2MCwicHJpbWFyeUxvY2F0aW9uIjp7ImlkIjoxfSwiZGlzcGxheU5hbWUiOiJGb3h4IiwibGV2ZWwiOjEsImNyZWRpdHMiOjAsInhwIjowfSwiaWF0IjoxNzIwODc3NjMwLCJleHAiOjIwMzY0NTM2MzB9.Xf0dJLWUhUtJvvvMc6h6JYke7N5G0_js_Yc4LoUlHMo


###

POST https://api-na.orcwood.com/public/login
content-type: application/json

{
    "steamId": 76561198393504470,
    "displayName": "Foxx"
}

###

GET https://api-new-america-ieqetiq36q-uc.a.run.app/game/locations
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo0LCJzdGVhbUlkIjo3NjU2MTE5ODM5MzUwNDQ2MCwicHJpbWFyeUxvY2F0aW9uIjp7ImlkIjoxfSwiZGlzcGxheU5hbWUiOiJGb3h4IiwibGV2ZWwiOjEsImNyZWRpdHMiOjAsInhwIjowfSwiaWF0IjoxNzIwODgwOTM1LCJleHAiOjIwMzY0NTY5MzV9.8qssuK1zP3gvn8xB6PbY0EOUpSx_0FUHU2qtXtoD6Sc
