GET http://localhost:8101/tutorial_users
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InR5cGUiOiJBTk9OWU1PVVMiLCJuYW1lIjoiQW5vbnltb3VzIn0sImlhdCI6MTY3Mjc0NzE1MSwiZXhwIjoxOTg4MzIzMTUxfQ.1Eybsth4k1aE_sBv_dz2XocJv6mtoBvRNX0gUJo9vGw

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}